source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'devise'
gem 'omniauth'
gem 'jquery-rails'
gem 'mysql'
gem 'ruby-debug'
gem 'prawn'
gem "resque", '1.15.0'
gem 'resque_mailer', '1.0.1'
gem 'redis'
gem 'redis-namespace'
gem 'yajl-ruby'
gem 'vegas'
gem 'sinatra'
gem 'whenever'
gem 'brstring'
gem 'json', '1.4.6'
gem 'levenshtein'
gem 'rcov'
gem 'rspec-rails'
gem 'fastercsv'

